"""add call analysis tables

Revision ID: fc61c8d9ecc6
Revises:
Created: 2026-08-28 11:03:15.735378+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fc61c8d9ecc6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerated from the ORM mapping, then reviewed: 7 tables, 7 indexes,
    # cascade deletes from calls, and a reversible downgrade.
    op.create_table(
        "calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("category_code", sa.String(length=64), nullable=False),
        sa.Column("resolution", sa.String(length=64), nullable=False),
        sa.Column("sentiment_start", sa.String(length=64), nullable=False),
        sa.Column("sentiment_end", sa.String(length=64), nullable=False),
        sa.Column("agent_name", sa.String(length=128), nullable=True),
        sa.Column("member_context", sa.Text(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("score_status", sa.String(length=64), nullable=False),
        sa.Column("tier", sa.String(length=64), nullable=False),
        sa.Column("total_positive", sa.Integer(), nullable=False),
        sa.Column("total_negative", sa.Integer(), nullable=False),
        sa.Column("applied_offset", sa.Integer(), nullable=False),
        sa.Column("gate_messages", sa.JSON(), nullable=False),
        sa.Column("triggered_gate_ids", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("signal_codes", sa.JSON(), nullable=False),
        sa.Column("rejected_marker_notes", sa.JSON(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=256), nullable=False),
        sa.Column("rubric_version", sa.String(length=64), nullable=False),
        sa.Column("analysed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calls")),
        sa.UniqueConstraint("reference", name="uq_calls_reference"),
    )
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.create_index("ix_calls_agent_name", ["agent_name"], unique=False)
        batch_op.create_index("ix_calls_category_code", ["category_code"], unique=False)
        batch_op.create_index("ix_calls_resolution", ["resolution"], unique=False)

    op.create_table(
        "analysis_layers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("call_id", sa.Integer(), nullable=False),
        sa.Column("layer", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("unavailable", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
            name=op.f("fk_analysis_layers_call_id_calls"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_layers")),
        sa.UniqueConstraint("call_id", "layer", name="uq_analysis_layers_call_id"),
    )
    op.create_table(
        "assist_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("call_id", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=64), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=64), nullable=False),
        sa.Column("at_turn_seq", sa.Integer(), nullable=True),
        sa.Column("timestamp_label", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
            name=op.f("fk_assist_events_call_id_calls"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assist_events")),
    )
    with op.batch_alter_table("assist_events", schema=None) as batch_op:
        batch_op.create_index("ix_assist_events_outcome", ["outcome"], unique=False)

    op.create_table(
        "broker_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("call_id", sa.Integer(), nullable=False),
        sa.Column("broker_name", sa.String(length=128), nullable=False),
        sa.Column("polarity", sa.String(length=64), nullable=False),
        sa.Column("basis", sa.String(length=64), nullable=False),
        sa.Column("issue", sa.Text(), nullable=False),
        sa.Column("evidence_turn_seq", sa.Integer(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
            name=op.f("fk_broker_signals_call_id_calls"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_signals")),
    )
    with op.batch_alter_table("broker_signals", schema=None) as batch_op:
        batch_op.create_index("ix_broker_signals_broker_name", ["broker_name"], unique=False)

    op.create_table(
        "l4_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("call_id", sa.Integer(), nullable=False),
        sa.Column("category_code", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=64), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=False),
        sa.Column("recommended_action", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_l4_signals_call_id_calls"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_l4_signals")),
    )
    with op.batch_alter_table("l4_signals", schema=None) as batch_op:
        batch_op.create_index("ix_l4_signals_category_code", ["category_code"], unique=False)

    op.create_table(
        "score_markers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("call_id", sa.Integer(), nullable=False),
        sa.Column("polarity", sa.String(length=64), nullable=False),
        sa.Column("dimension", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence_turn_seq", sa.Integer(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"],
            ["calls.id"],
            name=op.f("fk_score_markers_call_id_calls"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score_markers")),
    )
    with op.batch_alter_table("score_markers", schema=None) as batch_op:
        batch_op.create_index("ix_score_markers_dimension", ["dimension"], unique=False)

    op.create_table(
        "turns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("call_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("speaker_name", sa.String(length=128), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_turns_call_id_calls"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
        sa.UniqueConstraint("call_id", "seq", name="uq_turns_call_id"),
    )


def downgrade() -> None:
    # Autogenerated from the ORM mapping, then reviewed: 7 tables, 7 indexes,
    # cascade deletes from calls, and a reversible downgrade.
    op.drop_table("turns")
    with op.batch_alter_table("score_markers", schema=None) as batch_op:
        batch_op.drop_index("ix_score_markers_dimension")

    op.drop_table("score_markers")
    with op.batch_alter_table("l4_signals", schema=None) as batch_op:
        batch_op.drop_index("ix_l4_signals_category_code")

    op.drop_table("l4_signals")
    with op.batch_alter_table("broker_signals", schema=None) as batch_op:
        batch_op.drop_index("ix_broker_signals_broker_name")

    op.drop_table("broker_signals")
    with op.batch_alter_table("assist_events", schema=None) as batch_op:
        batch_op.drop_index("ix_assist_events_outcome")

    op.drop_table("assist_events")
    op.drop_table("analysis_layers")
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.drop_index("ix_calls_resolution")
        batch_op.drop_index("ix_calls_category_code")
        batch_op.drop_index("ix_calls_agent_name")

    op.drop_table("calls")
