/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyse a pasted transcript */
        post: operations["analyse_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List analysed calls */
        get: operations["list_calls_api_v1_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calls/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One call in full */
        get: operations["get_call_api_v1_calls__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How large the corpus is, and how much of it is analysed */
        get: operations["corpus_status_api_v1_corpus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent corpus runs */
        get: operations["list_runs_api_v1_corpus_runs_get"];
        put?: never;
        /** Start a corpus run */
        post: operations["start_run_api_v1_corpus_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One corpus run and every call in it */
        get: operations["get_run_api_v1_corpus_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a run to stop after the call in flight */
        post: operations["cancel_run_api_v1_corpus_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue a run that was cancelled or interrupted */
        post: operations["resume_run_api_v1_corpus_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live progress for a run, as Server-Sent Events */
        get: operations["stream_run_api_v1_corpus_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent performance */
        get: operations["get_agents_api_v1_dashboard_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/brokers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Broker scorecard */
        get: operations["get_brokers_api_v1_dashboard_brokers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What needs attention */
        get: operations["get_overview_api_v1_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** L4 signal distribution */
        get: operations["get_signals_api_v1_dashboard_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report application and dependency health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List model providers and their current availability */
        get: operations["list_providers_api_v1_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Controlled vocabularies */
        get: operations["get_taxonomy_api_v1_taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentResponse */
        AgentResponse: {
            /** Agent Name */
            agent_name: string;
            /** Average Score */
            average_score: number;
            /** Call Count */
            call_count: number;
            /** Escalated */
            escalated: number;
            /** Max Score */
            max_score: number;
            /** Min Score */
            min_score: number;
            /** Note */
            note: string | null;
            /** Partially Resolved */
            partially_resolved: number;
            /** Resolved */
            resolved: number;
            /**
             * Tier
             * @description Null when the sample is too small to rate the agent fairly.
             */
            tier: string | null;
            /** Unresolved */
            unresolved: number;
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Agent Name */
            agent_name: string | null;
            /** Assist Events */
            assist_events: components["schemas"]["AssistEventResponse"][];
            /** Broker Signals */
            broker_signals: components["schemas"]["BrokerSignalResponse"][];
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Duration Minutes */
            duration_minutes: number | null;
            /**
             * Id
             * @description Database id, for linking straight to the call.
             */
            id: number;
            /** L4 Signals */
            l4_signals: components["schemas"]["L4SignalResponse"][];
            /** Layers */
            layers: components["schemas"]["LayerResponse"][];
            /** Markers */
            markers: components["schemas"]["MarkerResponse"][];
            /** Member Context */
            member_context: string | null;
            provenance: components["schemas"]["ProvenanceResponse"];
            /** Reference */
            reference: string;
            /**
             * Rejected Attribution Notes
             * @description Broker attributions discarded because their evidence did not check out.
             */
            rejected_attribution_notes: string[];
            /**
             * Rejected Marker Notes
             * @description Observations discarded because their evidence did not check out.
             */
            rejected_marker_notes: string[];
            /** Resolution */
            resolution: string;
            score: components["schemas"]["ScoreResponse"];
            /** Sentiment End */
            sentiment_end: string;
            /** Sentiment Start */
            sentiment_start: string;
            /** Signal Codes */
            signal_codes: string[];
            /** Source */
            source: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Transcript */
            transcript: components["schemas"]["TurnResponse"][];
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Model
             * @description Model override for this analysis.
             */
            model?: string | null;
            /**
             * Provider
             * @description Provider name. Defaults to the configured provider.
             */
            provider?: string | null;
            /**
             * Transcript
             * @description Pasted transcript, one speaker turn per line as 'Speaker: text'.
             */
            transcript: string;
        };
        /** AssistEventResponse */
        AssistEventResponse: {
            /** At Turn Seq */
            at_turn_seq: number | null;
            /** Is Gap */
            is_gap: boolean;
            /** Outcome */
            outcome: string;
            /** Recommendation */
            recommendation: string;
            /** Severity */
            severity: string;
            /** Timestamp Label */
            timestamp_label: string | null;
            /** Trigger */
            trigger: string;
        };
        /** AttentionItemResponse */
        AttentionItemResponse: {
            /** Count */
            count: number;
            /** Owner */
            owner: string;
            /** References */
            references: string[];
            /** Rule Id */
            rule_id: string;
            /** Severity */
            severity: string;
            /** Subject */
            subject: string;
            /** Title */
            title: string;
            /** Unresolved */
            unresolved: number;
            /** Why */
            why: string;
        };
        /** BrokerResponse */
        BrokerResponse: {
            /** Broker Name */
            broker_name: string;
            /** Call References */
            call_references: string[];
            /** Is Net Positive */
            is_net_positive: boolean;
            /** Negative */
            negative: number;
            /** Positive */
            positive: number;
            /** Signals */
            signals: number;
        };
        /** BrokerSignalResponse */
        BrokerSignalResponse: {
            /** Basis */
            basis: string;
            /** Broker Name */
            broker_name: string;
            /** Evidence Turn Seq */
            evidence_turn_seq: number;
            /** Issue */
            issue: string;
            /** Polarity */
            polarity: string;
            /** Quote */
            quote: string;
        };
        /** CallSummaryResponse */
        CallSummaryResponse: {
            /** Agent Name */
            agent_name: string | null;
            /**
             * Analysed At
             * Format: date-time
             */
            analysed_at: string;
            /** Broker Names */
            broker_names: string[];
            /** Category */
            category: string;
            /** Id */
            id: number;
            /** Reference */
            reference: string;
            /** Resolution */
            resolution: string;
            /** Score */
            score: number;
            /** Score Status */
            score_status: string;
            /** Signal Codes */
            signal_codes: string[];
            /** Source */
            source: string;
            /** Summary */
            summary: string;
            /** Tier */
            tier: string;
            /** Title */
            title: string;
        };
        /** CallsPageResponse */
        CallsPageResponse: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["CallSummaryResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Matching calls, before paging.
             */
            total: number;
        };
        /** CategoryEntry */
        CategoryEntry: {
            /** Code */
            code: string;
            /** Description */
            description: string | null;
            /** Label */
            label: string;
        };
        /** CategoryResponse */
        CategoryResponse: {
            /** Code */
            code: string;
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Percentage Of Total */
            percentage_of_total: number;
            /** Unresolved */
            unresolved: number;
        };
        /** ComponentHealthResponse */
        ComponentHealthResponse: {
            /** Detail */
            detail?: string | null;
            /** Name */
            name: string;
            status: components["schemas"]["ComponentStatus"];
        };
        /**
         * ComponentStatus
         * @description Outcome of probing a single component.
         * @enum {string}
         */
        ComponentStatus: "up" | "down";
        /** CorpusStatusResponse */
        CorpusStatusResponse: {
            /** Active Run Id */
            active_run_id: number | null;
            /** Analysed Calls */
            analysed_calls: number;
            /**
             * Location
             * @description Where the corpus is read from.
             */
            location: string;
            /** Outstanding */
            outstanding: number;
            /** Total Calls */
            total_calls: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Application */
            application: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Components */
            components?: components["schemas"]["ComponentHealthResponse"][];
            /** Environment */
            environment: string;
            status: components["schemas"]["ComponentStatus"];
            /** Version */
            version: string;
        };
        /** HistogramBinResponse */
        HistogramBinResponse: {
            /** Count */
            count: number;
            /** Is Below Threshold */
            is_below_threshold: boolean;
            /** Label */
            label: string;
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
        };
        /** HistogramResponse */
        HistogramResponse: {
            /** Below Threshold Count */
            below_threshold_count: number;
            /** Bins */
            bins: components["schemas"]["HistogramBinResponse"][];
            /** Peak */
            peak: number;
            /** Total */
            total: number;
        };
        /** L4CategoryEntry */
        L4CategoryEntry: {
            /** Code */
            code: string;
            /** Default Severity */
            default_severity: string;
            /** Label */
            label: string;
            /** Owner */
            owner: string;
        };
        /** L4SignalResponse */
        L4SignalResponse: {
            /** Category */
            category: string;
            /** Narrative */
            narrative: string;
            /** Owner */
            owner: string;
            /** Recommended Action */
            recommended_action: string | null;
            /** Severity */
            severity: string;
        };
        /** LayerResponse */
        LayerResponse: {
            /** Layer */
            layer: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** MarkerResponse */
        MarkerResponse: {
            /** Description */
            description: string;
            /** Dimension */
            dimension: string;
            /** Evidence Turn Seq */
            evidence_turn_seq: number;
            /** Polarity */
            polarity: string;
            /** Quote */
            quote: string;
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Broker Signal Count */
            broker_signal_count: number;
            /** Distinct Broker Count */
            distinct_broker_count: number;
            /** Escalation Rate */
            escalation_rate: number;
            /**
             * First Contact Resolution Rate
             * @description RESOLVED as a percentage of all calls. Excludes PARTIALLY RESOLVED.
             */
            first_contact_resolution_rate: number;
            /**
             * Mean Score
             * @description Reported alongside the median because the distribution is bimodal; one number alone would hide the low cluster.
             */
            mean_score: number;
            /** Median Score */
            median_score: number;
            /** Provisional Score Count */
            provisional_score_count: number;
            /** Total Calls */
            total_calls: number;
            /** Unresolved Rate */
            unresolved_rate: number;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Attention */
            attention: components["schemas"]["AttentionItemResponse"][];
            /** Categories */
            categories: components["schemas"]["CategoryResponse"][];
            histogram: components["schemas"]["HistogramResponse"];
            metrics: components["schemas"]["MetricsResponse"];
            /**
             * Taxonomy Coverage
             * @description Share of calls landing in a defined category. Below 90% means the taxonomy needs revising, not the chart.
             */
            taxonomy_coverage: number;
        };
        /** OwnerLoadResponse */
        OwnerLoadResponse: {
            /** Count */
            count: number;
            /** Owner */
            owner: string;
        };
        /** ProgressResponse */
        ProgressResponse: {
            /** Cancelled */
            cancelled: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Finished */
            finished: number;
            /** Pending */
            pending: number;
            /** Percent Complete */
            percent_complete: number;
            /** Remaining */
            remaining: number;
            /** Running */
            running: number;
            /** Skipped */
            skipped: number;
            /** Total */
            total: number;
        };
        /** ProvenanceResponse */
        ProvenanceResponse: {
            /**
             * Analysed At
             * Format: date-time
             */
            analysed_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Rubric Version */
            rubric_version: string;
        };
        /** ProviderResponse */
        ProviderResponse: {
            /**
             * Billable
             * @description Whether running against this provider is charged for per token.
             */
            billable: boolean;
            /**
             * Configured
             * @description Whether the provider's required settings are present.
             */
            configured: boolean;
            /** Detail */
            detail?: string | null;
            /**
             * Implemented
             * @description False for providers registered but not built.
             */
            implemented: boolean;
            /** Is Default */
            is_default: boolean;
            /** Model */
            model: string;
            /** Name */
            name: string;
            /**
             * Reachable
             * @description Whether it answered a probe just now.
             */
            reachable: boolean;
            /**
             * Selectable
             * @description Whether an analysis may be run against it.
             */
            selectable: boolean;
        };
        /** ProvidersResponse */
        ProvidersResponse: {
            /** Default */
            default: string;
            /** Providers */
            providers: components["schemas"]["ProviderResponse"][];
        };
        /** RunItemResponse */
        RunItemResponse: {
            /** Call Id */
            call_id: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Finished At */
            finished_at: string | null;
            /** Message */
            message: string;
            /** Reference */
            reference: string;
            /** Source Id */
            source_id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** RunResponse */
        RunResponse: {
            /** Can Resume */
            can_resume: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Force */
            force: boolean;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Items */
            items: components["schemas"]["RunItemResponse"][];
            /** Message */
            message: string;
            /** Model */
            model: string;
            progress: components["schemas"]["ProgressResponse"];
            /** Provider */
            provider: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** RunSummaryResponse */
        RunSummaryResponse: {
            /** Can Resume */
            can_resume: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Force */
            force: boolean;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Message */
            message: string;
            /** Model */
            model: string;
            progress: components["schemas"]["ProgressResponse"];
            /** Provider */
            provider: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** ScoreResponse */
        ScoreResponse: {
            /** Applied Offset */
            applied_offset: number;
            /** Gate Messages */
            gate_messages: string[];
            /** Status */
            status: string;
            /** Tier */
            tier: string;
            /** Total Negative */
            total_negative: number;
            /** Total Positive */
            total_positive: number;
            /** Value */
            value: number;
        };
        /** SignalEntryResponse */
        SignalEntryResponse: {
            /** Code */
            code: string;
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Owner */
            owner: string;
            /** Percentage Of Corpus */
            percentage_of_corpus: number;
        };
        /** SignalTypeEntry */
        SignalTypeEntry: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Severity */
            severity: string;
        };
        /** SignalsResponse */
        SignalsResponse: {
            /**
             * Categories
             * @description Every configured L4 category, including those with no signals — the absence is shown rather than implied.
             */
            categories: components["schemas"]["SignalEntryResponse"][];
            /** Owners */
            owners: components["schemas"]["OwnerLoadResponse"][];
        };
        /** StartRunRequest */
        StartRunRequest: {
            /**
             * Acknowledge Cost
             * @description Required to run against a provider that charges per token.
             * @default false
             */
            acknowledge_cost: boolean;
            /**
             * Force
             * @description Re-analyse calls that already have an analysis, replacing them.
             * @default false
             */
            force: boolean;
            /**
             * Model
             * @description Model override for this run.
             */
            model?: string | null;
            /**
             * Provider
             * @description Provider name. Defaults to the configured provider.
             */
            provider?: string | null;
        };
        /** TaxonomyResponse */
        TaxonomyResponse: {
            /** Categories */
            categories: components["schemas"]["CategoryEntry"][];
            /** L4 Categories */
            l4_categories: components["schemas"]["L4CategoryEntry"][];
            /** Resolutions */
            resolutions: string[];
            /** Rubric Version */
            rubric_version: string;
            /** Sentiment States */
            sentiment_states: string[];
            /** Severities */
            severities: string[];
            /** Signal Types */
            signal_types: components["schemas"]["SignalTypeEntry"][];
            tiers: components["schemas"]["TierThresholdsEntry"];
        };
        /** TierThresholdsEntry */
        TierThresholdsEntry: {
            /** Average */
            average: number;
            /** Good */
            good: number;
            /** Min Calls For Tier Rating */
            min_calls_for_tier_rating: number;
        };
        /** TurnResponse */
        TurnResponse: {
            /** Role */
            role: string;
            /** Seq */
            seq: number;
            /** Speaker Name */
            speaker_name: string | null;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyse_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calls_api_v1_calls_get: {
        parameters: {
            query?: {
                /** @description Call category code. */
                category?: string | null;
                /** @description Agent name. */
                agent?: string | null;
                /** @description Outcome, e.g. UNRESOLVED. */
                resolution?: string | null;
                max_score?: number | null;
                min_score?: number | null;
                has_broker_signal?: boolean | null;
                /** @description Signal code, e.g. clinical_risk. */
                signal?: string | null;
                /** @description Matches title, summary or reference. */
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallsPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_call_api_v1_calls__call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    corpus_status_api_v1_corpus_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusStatusResponse"];
                };
            };
        };
    };
    list_runs_api_v1_corpus_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_v1_corpus_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_corpus_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_corpus_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_v1_corpus_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_v1_corpus_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agents_api_v1_dashboard_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"][];
                };
            };
        };
    };
    get_brokers_api_v1_dashboard_brokers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerResponse"][];
                };
            };
        };
    };
    get_overview_api_v1_dashboard_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    get_signals_api_v1_dashboard_signals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalsResponse"];
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A component is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_providers_api_v1_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersResponse"];
                };
            };
        };
    };
    get_taxonomy_api_v1_taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyResponse"];
                };
            };
        };
    };
}
