/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyse a pasted transcript */
        post: operations["analyse_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List analyzed calls */
        get: operations["list_calls_api_v1_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calls/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One call in full */
        get: operations["get_call_api_v1_calls__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How large the corpus is, and how much of it is analyzed */
        get: operations["corpus_status_api_v1_corpus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Discard every analyzed call, keeping ground truth
         * @description Empty the corpus so it can be re-analyzed from nothing.
         *
         *     Refused with a 409 while a run is working: the worker would be writing to
         *     rows this is deleting.
         */
        delete: operations["clear_corpus_api_v1_corpus_analyses_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Corpora that have been imported, newest first */
        get: operations["list_corpus_imports_api_v1_corpus_imports_get"];
        put?: never;
        /**
         * Convert an uploaded corpus document into sample call files
         * @description Extract every call from a corpus PDF and save it as corpus markdown.
         *
         *     Saved under its own name in the import library, never over the corpus in
         *     use: the stored analyses are only meaningful against the transcripts they
         *     were made from, so replacing those silently would leave the dashboard
         *     describing calls that no longer exist.
         *
         *     Nothing is analysed here. Import produces files; a run spends money.
         */
        post: operations["import_corpus_api_v1_corpus_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent corpus runs */
        get: operations["list_runs_api_v1_corpus_runs_get"];
        put?: never;
        /** Start a corpus run */
        post: operations["start_run_api_v1_corpus_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One corpus run and every call in it */
        get: operations["get_run_api_v1_corpus_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a run to stop after the call in flight */
        post: operations["cancel_run_api_v1_corpus_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue a run that was cancelled or interrupted */
        post: operations["resume_run_api_v1_corpus_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live progress for a run, as Server-Sent Events */
        get: operations["stream_run_api_v1_corpus_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent performance */
        get: operations["get_agents_api_v1_dashboard_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/brokers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Broker scorecard */
        get: operations["get_brokers_api_v1_dashboard_brokers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/effort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What getting an answer costs a member */
        get: operations["get_effort_api_v1_dashboard_effort_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/members-at-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Members showing signs of leaving, with the evidence */
        get: operations["get_members_at_risk_api_v1_dashboard_members_at_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What needs attention */
        get: operations["get_overview_api_v1_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/pulse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which way the centre is moving, week by week */
        get: operations["get_pulse_api_v1_dashboard_pulse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/resolution-time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How long it takes to resolve a member's problem, by category */
        get: operations["get_resolution_time_api_v1_dashboard_resolution_time_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** L4 signal distribution */
        get: operations["get_signals_api_v1_dashboard_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/time-value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the time on calls bought, in minutes */
        get: operations["get_time_value_api_v1_dashboard_time_value_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/work-mix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who calls, and when the calls come */
        get: operations["get_work_mix_api_v1_dashboard_work_mix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report application and dependency health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List model providers and their current availability */
        get: operations["list_providers_api_v1_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Controlled vocabularies */
        get: operations["get_taxonomy_api_v1_taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentResponse */
        AgentResponse: {
            /** Agent Name */
            agent_name: string;
            /** Average Score */
            average_score: number;
            /** Call Count */
            call_count: number;
            /** Escalated */
            escalated: number;
            /** Max Score */
            max_score: number;
            /** Min Score */
            min_score: number;
            /** Note */
            note: string | null;
            /** Partially Resolved */
            partially_resolved: number;
            /** Resolved */
            resolved: number;
            /**
             * Tier
             * @description Null when the sample is too small to rate the agent fairly.
             */
            tier: string | null;
            /** Unresolved */
            unresolved: number;
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Agent Name */
            agent_name: string | null;
            /** Assist Events */
            assist_events: components["schemas"]["AssistEventResponse"][];
            /** Broker Signals */
            broker_signals: components["schemas"]["BrokerSignalResponse"][];
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Duration Minutes */
            duration_minutes: number | null;
            /**
             * Id
             * @description Database id, for linking straight to the call.
             */
            id: number;
            /** L4 Signals */
            l4_signals: components["schemas"]["L4SignalResponse"][];
            /** Layers */
            layers: components["schemas"]["LayerResponse"][];
            /** Markers */
            markers: components["schemas"]["MarkerResponse"][];
            /** Member Context */
            member_context: string | null;
            provenance: components["schemas"]["ProvenanceResponse"];
            /** Reference */
            reference: string;
            /**
             * Rejected Attribution Notes
             * @description Broker attributions discarded because their evidence did not check out.
             */
            rejected_attribution_notes: string[];
            /**
             * Rejected Marker Notes
             * @description Observations discarded because their evidence did not check out.
             */
            rejected_marker_notes: string[];
            /** Resolution */
            resolution: string;
            score: components["schemas"]["ScoreResponse"];
            /** Sentiment End */
            sentiment_end: string;
            /** Sentiment Start */
            sentiment_start: string;
            /** Signal Codes */
            signal_codes: string[];
            /** Source */
            source: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Transcript */
            transcript: components["schemas"]["TurnResponse"][];
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Model
             * @description Model override for this analysis.
             */
            model?: string | null;
            /**
             * Provider
             * @description Provider name. Defaults to the configured provider.
             */
            provider?: string | null;
            /**
             * Transcript
             * @description Pasted transcript, one speaker turn per line as 'Speaker: text'.
             */
            transcript: string;
        };
        /** AssistEventResponse */
        AssistEventResponse: {
            /** At Turn Seq */
            at_turn_seq: number | null;
            /** Is Gap */
            is_gap: boolean;
            /** Outcome */
            outcome: string;
            /** Recommendation */
            recommendation: string;
            /** Severity */
            severity: string;
            /** Timestamp Label */
            timestamp_label: string | null;
            /** Trigger */
            trigger: string;
        };
        /** AttentionItemResponse */
        AttentionItemResponse: {
            /**
             * Call Filter
             * @description The calls list query that returns exactly the calls this item counted, as query-string parameters. Sent from here rather than rebuilt by the client from the rule id: the rule kinds are a server-side vocabulary, and a client mapping them itself would quietly produce a dead link the first time a kind is added. Empty when the item's subject has no filter, which is a gap to close rather than a state to design for.
             */
            call_filter: {
                [key: string]: string;
            };
            /** Count */
            count: number;
            /** Owner */
            owner: string;
            /** References */
            references: string[];
            /** Rule Id */
            rule_id: string;
            /** Severity */
            severity: string;
            /** Subject */
            subject: string;
            /** Title */
            title: string;
            /** Unresolved */
            unresolved: number;
            /** Why */
            why: string;
        };
        /** Body_import_corpus_api_v1_corpus_imports_post */
        Body_import_corpus_api_v1_corpus_imports_post: {
            /**
             * File
             * @description A call-corpus PDF.
             */
            file: string;
        };
        /** BrokerResponse */
        BrokerResponse: {
            /** Broker Name */
            broker_name: string;
            /** Call References */
            call_references: string[];
            /**
             * Discarded
             * @description Attributions naming this broker that failed evidence checking and were never recorded. Not included in the signal counts.
             * @default 0
             */
            discarded: number;
            /** Is Net Positive */
            is_net_positive: boolean;
            /** Negative */
            negative: number;
            /** Positive */
            positive: number;
            /** Signals */
            signals: number;
        };
        /** BrokerSignalResponse */
        BrokerSignalResponse: {
            /** Basis */
            basis: string;
            /** Broker Name */
            broker_name: string;
            /** Evidence Turn Seq */
            evidence_turn_seq: number;
            /** Issue */
            issue: string;
            /** Polarity */
            polarity: string;
            /** Quote */
            quote: string;
        };
        /**
         * Bucket
         * @description The period one point covers.
         *
         *     A month is not four weeks added up. Every figure here is computed from the
         *     calls in the bucket, so a month's median score is the median of its own
         *     calls -- the median of four weekly medians is a different number, and not
         *     one the corpus contains. That is why picking a month re-buckets from the
         *     calls rather than folding the weekly series.
         * @enum {string}
         */
        Bucket: "week" | "month";
        /**
         * CallSort
         * @description A column the calls list may be ordered by.
         *
         *     An allowlist, not a column name passed through: the value arrives from a
         *     query string, and mapping it to a column here is what stops it reaching SQL.
         * @enum {string}
         */
        CallSort: "severity" | "reference" | "category" | "agent" | "resolution" | "score" | "analysed_at";
        /** CallSummaryResponse */
        CallSummaryResponse: {
            /** Agent Name */
            agent_name: string | null;
            /**
             * Analysed At
             * Format: date-time
             */
            analysed_at: string;
            /** Broker Names */
            broker_names: string[];
            /** Caller Type */
            caller_type?: string | null;
            /** Category */
            category: string;
            /** Id */
            id: number;
            /** Member Id */
            member_id?: string | null;
            /** Member Name */
            member_name?: string | null;
            /** Reference */
            reference: string;
            /** Resolution */
            resolution: string;
            /** Score */
            score: number;
            /** Score Status */
            score_status: string;
            /** Signal Codes */
            signal_codes: string[];
            /** Source */
            source: string;
            /** Summary */
            summary: string;
            /** Tier */
            tier: string;
            /** Title */
            title: string;
        };
        /** CallerBreakdownResponse */
        CallerBreakdownResponse: {
            /** Average Handle Minutes */
            average_handle_minutes: number | null;
            /** Average Score */
            average_score: number;
            /** Caller Type */
            caller_type: string;
            /** Calls */
            calls: number;
            /** Resolution Rate */
            resolution_rate: number;
            /** Share */
            share: number;
        };
        /** CallsPageResponse */
        CallsPageResponse: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["CallSummaryResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Matching calls, before paging.
             */
            total: number;
        };
        /** CategoryEntry */
        CategoryEntry: {
            /** Code */
            code: string;
            /** Description */
            description: string | null;
            /** Label */
            label: string;
        };
        /** CategoryMinutesResponse */
        CategoryMinutesResponse: {
            /**
             * By Outcome
             * @description Always in the same order, worst last, so a category's segments do not shuffle when its mix changes. Zero-minute outcomes are kept.
             */
            by_outcome: components["schemas"]["OutcomeMinutesResponse"][];
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Resolved Minutes */
            resolved_minutes: number;
            /** Total Minutes */
            total_minutes: number;
            /** Unproductive Minutes */
            unproductive_minutes: number;
            /** Unproductive Share */
            unproductive_share: number;
        };
        /** CategoryResolutionTimeResponse */
        CategoryResolutionTimeResponse: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Longest Minutes */
            longest_minutes: number;
            /** Median Minutes */
            median_minutes: number;
            /** Resolved Calls */
            resolved_calls: number;
        };
        /** CategoryResponse */
        CategoryResponse: {
            /** Code */
            code: string;
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Percentage Of Total */
            percentage_of_total: number;
            /** Unresolved */
            unresolved: number;
        };
        /** ClearedCorpusResponse */
        ClearedCorpusResponse: {
            /**
             * Calls
             * @description Analyzed calls removed.
             */
            calls: number;
            /**
             * Ground Truth Kept
             * @description Always true. Ground truth is hand-labelled and cannot be regenerated by re-analysis, so it is never part of a clear.
             * @default true
             */
            ground_truth_kept: boolean;
            /**
             * Runs
             * @description Corpus run records removed, with their items.
             */
            runs: number;
        };
        /** ComponentHealthResponse */
        ComponentHealthResponse: {
            /** Detail */
            detail?: string | null;
            /** Name */
            name: string;
            status: components["schemas"]["ComponentStatus"];
        };
        /**
         * ComponentStatus
         * @description Outcome of probing a single component.
         * @enum {string}
         */
        ComponentStatus: "up" | "down";
        /** CorpusImportResponse */
        CorpusImportResponse: {
            /** Calls */
            calls: components["schemas"]["ImportedCallResponse"][];
            /** Directory */
            directory: string;
            /**
             * Name
             * @description Directory this corpus was saved as.
             */
            name: string;
            /** Total */
            total: number;
        };
        /** CorpusStatusResponse */
        CorpusStatusResponse: {
            /** Active Run Id */
            active_run_id: number | null;
            /** Analysed Calls */
            analysed_calls: number;
            /**
             * Location
             * @description Where the corpus is read from.
             */
            location: string;
            /** Outstanding */
            outstanding: number;
            /** Total Calls */
            total_calls: number;
        };
        /** CorpusVersionResponse */
        CorpusVersionResponse: {
            /** Directory */
            directory: string;
            /** Files */
            files: number;
            /** Name */
            name: string;
        };
        /** DurationBandResponse */
        DurationBandResponse: {
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Lower */
            lower: number;
            /**
             * Upper
             * @description Exclusive upper bound in minutes; null for the final open-ended band. Half-open like the score bins, so '10-20' holds 10 up to 19.
             */
            upper?: number | null;
        };
        /** EffortResponse */
        EffortResponse: {
            /** Calls By Repeat Members */
            calls_by_repeat_members: number;
            /** Calls With Duration */
            calls_with_duration: number;
            /**
             * Identified Members
             * @description Members whose identifier was stated in the call. Calls without one are excluded rather than grouped, since unknown members are different people.
             */
            identified_members: number;
            /**
             * Long Call Count
             * @description Calls at or beyond twice the median, which is where 'long' starts.
             */
            long_call_count: number;
            /** Long Call Threshold */
            long_call_threshold: number;
            /** Longest Minutes */
            longest_minutes: number;
            /** Mean Minutes */
            mean_minutes: number;
            /** Median Minutes */
            median_minutes: number;
            /**
             * Median Minutes To Answer
             * @description Median minutes a member spent across all their calls before one of them resolved their issue. Members still waiting are excluded, not counted as zero.
             */
            median_minutes_to_answer: number;
            /**
             * Members With Answer
             * @description Identified members who reached a resolution. The population the time-to-answer figure is measured over.
             */
            members_with_answer: number;
            /**
             * Members Without Answer
             * @description Identified members with no resolved call. Their clock has not stopped, so folding them in would shorten the reported time the longer they are left waiting.
             */
            members_without_answer: number;
            /**
             * Repeat Contact Rate
             * @description Share of identified members who called more than once, as a percentage.
             */
            repeat_contact_rate: number;
            /** Repeat Members */
            repeat_members: number;
        };
        /** FailureModeResponse */
        FailureModeResponse: {
            /** Average Score */
            average_score: number;
            /** Calls */
            calls: number;
            /** Minutes */
            minutes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Application */
            application: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Components */
            components?: components["schemas"]["ComponentHealthResponse"][];
            /** Environment */
            environment: string;
            status: components["schemas"]["ComponentStatus"];
            /** Version */
            version: string;
        };
        /** HistogramBinResponse */
        HistogramBinResponse: {
            /** Count */
            count: number;
            /** Is Below Threshold */
            is_below_threshold: boolean;
            /** Label */
            label: string;
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
        };
        /** HistogramResponse */
        HistogramResponse: {
            /** Below Threshold Count */
            below_threshold_count: number;
            /** Bins */
            bins: components["schemas"]["HistogramBinResponse"][];
            /** Peak */
            peak: number;
            /** Total */
            total: number;
        };
        /** HourlyPointResponse */
        HourlyPointResponse: {
            /**
             * Average Handle Minutes
             * @description Mean handle time for this hour in minutes, over the calls that stated one. Null where none did — an hour that is unmeasured, not an hour that is instant.
             */
            average_handle_minutes: number | null;
            /** Average Score */
            average_score: number | null;
            /** Calls */
            calls: number;
            /** Hour */
            hour: number;
            /**
             * Is Thin
             * @description Too few calls in this hour to read anything into.
             */
            is_thin: boolean;
            /** Label */
            label: string;
            /** Resolution Rate */
            resolution_rate: number | null;
        };
        /** ImportedCallResponse */
        ImportedCallResponse: {
            /** Agent */
            agent: string | null;
            /**
             * Broker
             * @description Broker signal as 'Name: what they did', if any.
             */
            broker: string | null;
            /** Caller */
            caller: string | null;
            /** Filename */
            filename: string;
            /**
             * Has Panel
             * @description Whether the authored insights panel came through.
             */
            has_panel: boolean;
            /** Number */
            number: number;
            /** Queue */
            queue: string | null;
            /**
             * Reference
             * @description The reference a corpus run would store this call under.
             */
            reference: string;
            /**
             * Repeat
             * @description Whether this call is marked as a repeat contact.
             */
            repeat: boolean;
            /** Resolution */
            resolution: string | null;
            /** Score */
            score: number | null;
            /** Tier */
            tier: string | null;
            /** Title */
            title: string;
            /**
             * Turns
             * @description Non-blank transcript lines extracted for this call.
             */
            turns: number;
        };
        /** L4CategoryEntry */
        L4CategoryEntry: {
            /** Code */
            code: string;
            /** Default Severity */
            default_severity: string;
            /** Label */
            label: string;
            /** Owner */
            owner: string;
        };
        /** L4SignalResponse */
        L4SignalResponse: {
            /** Category */
            category: string;
            /** Narrative */
            narrative: string;
            /** Owner */
            owner: string;
            /** Recommended Action */
            recommended_action: string | null;
            /** Severity */
            severity: string;
        };
        /** LayerResponse */
        LayerResponse: {
            /** Layer */
            layer: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** MarkerResponse */
        MarkerResponse: {
            /** Description */
            description: string;
            /** Dimension */
            dimension: string;
            /** Evidence Turn Seq */
            evidence_turn_seq: number;
            /** Polarity */
            polarity: string;
            /** Quote */
            quote: string;
        };
        /** MemberAtRiskResponse */
        MemberAtRiskResponse: {
            /** Call Count */
            call_count: number;
            /** Factor Labels */
            factor_labels: string[];
            /**
             * Factors
             * @description Machine-readable risk factor codes observed for this member.
             */
            factors: string[];
            /** Latest Reference */
            latest_reference: string;
            /** Lowest Score */
            lowest_score: number;
            /** Member Id */
            member_id: string;
            /**
             * Member Name
             * @description The member's name where a call stated one. Null otherwise — the identifier is always known, the name is not.
             */
            member_name?: string | null;
            /** References */
            references: string[];
        };
        /** MembersAtRiskResponse */
        MembersAtRiskResponse: {
            /**
             * Basis
             * @description What this list is. Stated on the response because a client must not present it as a prediction: no factor here has been measured against an actual departure.
             * @default Observed warning signs, not a prediction. Ranked by how many signs a member shows. No weighting has been validated against real churn.
             */
            basis: string;
            /**
             * Factor Vocabulary
             * @description Every factor this system can observe, in a fixed order, whether or not any member is currently showing it. A client drawing a column per factor takes them from here: a factor added to the domain and not to the client would otherwise go unread with nothing to show for it, and an absent column is indistinguishable from a column of no findings.
             */
            factor_vocabulary: components["schemas"]["RiskFactorResponse"][];
            /** Members */
            members: components["schemas"]["MemberAtRiskResponse"][];
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Broker Signal Count */
            broker_signal_count: number;
            /** Distinct Broker Count */
            distinct_broker_count: number;
            /** Escalation Rate */
            escalation_rate: number;
            /**
             * First Contact Resolution Rate
             * @description RESOLVED as a percentage of all calls. Excludes PARTIALLY RESOLVED.
             */
            first_contact_resolution_rate: number;
            /**
             * Mean Score
             * @description Reported alongside the median because the distribution is bimodal; one number alone would hide the low cluster.
             */
            mean_score: number;
            /** Median Score */
            median_score: number;
            /** Provisional Score Count */
            provisional_score_count: number;
            /** Total Calls */
            total_calls: number;
            /** Unresolved Rate */
            unresolved_rate: number;
        };
        /** OutcomeMinutesResponse */
        OutcomeMinutesResponse: {
            /** Minutes */
            minutes: number;
            /** Resolution */
            resolution: string;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /** Attention */
            attention: components["schemas"]["AttentionItemResponse"][];
            /** Categories */
            categories: components["schemas"]["CategoryResponse"][];
            histogram: components["schemas"]["HistogramResponse"];
            metrics: components["schemas"]["MetricsResponse"];
            /**
             * Taxonomy Coverage
             * @description Share of calls landing in a defined category. Below 90% means the taxonomy needs revising, not the chart.
             */
            taxonomy_coverage: number;
        };
        /** OwnerLoadResponse */
        OwnerLoadResponse: {
            /** Count */
            count: number;
            /** Owner */
            owner: string;
        };
        /** ProgressResponse */
        ProgressResponse: {
            /** Cancelled */
            cancelled: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Finished */
            finished: number;
            /** Pending */
            pending: number;
            /** Percent Complete */
            percent_complete: number;
            /** Remaining */
            remaining: number;
            /** Running */
            running: number;
            /** Skipped */
            skipped: number;
            /** Total */
            total: number;
        };
        /** ProvenanceResponse */
        ProvenanceResponse: {
            /**
             * Analysed At
             * Format: date-time
             */
            analysed_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Rubric Version */
            rubric_version: string;
        };
        /** ProviderResponse */
        ProviderResponse: {
            /**
             * Billable
             * @description Whether running against this provider is charged for per token.
             */
            billable: boolean;
            /**
             * Configured
             * @description Whether the provider's required settings are present.
             */
            configured: boolean;
            /** Detail */
            detail?: string | null;
            /**
             * Implemented
             * @description False for providers registered but not built.
             */
            implemented: boolean;
            /** Is Default */
            is_default: boolean;
            /**
             * Local
             * @description Whether transcripts stay inside this environment. False means calls are sent to a third party, which is a statement about member health conversations rather than about cost.
             * @default false
             */
            local: boolean;
            /** Model */
            model: string;
            /** Name */
            name: string;
            /**
             * Reachable
             * @description Whether it answered a probe just now.
             */
            reachable: boolean;
            /**
             * Selectable
             * @description Whether an analysis may be run against it.
             */
            selectable: boolean;
        };
        /** ProvidersResponse */
        ProvidersResponse: {
            /** Default */
            default: string;
            /** Providers */
            providers: components["schemas"]["ProviderResponse"][];
        };
        /** PulseResponse */
        PulseResponse: {
            /**
             * Available Months
             * @description Every month that actually contains a call, oldest first, as first-of-month dates. Not the same set as the months of `available_weeks`: a week starting 31 August whose calls all fall in September would otherwise offer an August the corpus cannot answer for.
             */
            available_months: string[];
            /**
             * Available Weeks
             * @description Every week the corpus spans, oldest first — what a period picker offers, as distinct from `points`, which is only the anchored window.
             */
            available_weeks: string[];
            delta: components["schemas"]["TrendDeltaResponse"] | null;
            latest: components["schemas"]["TrendPointResponse"] | null;
            /** Points */
            points: components["schemas"]["TrendPointResponse"][];
            previous: components["schemas"]["TrendPointResponse"] | null;
            sentiment: components["schemas"]["SentimentMovementResponse"];
            /** Undated Calls */
            undated_calls: number;
        };
        /** ResolutionTimeResponse */
        ResolutionTimeResponse: {
            /** Bands */
            bands: components["schemas"]["DurationBandResponse"][];
            /**
             * Categories
             * @description Slowest first. Every configured category appears, including those that have resolved nothing.
             */
            categories: components["schemas"]["CategoryResolutionTimeResponse"][];
            /** Longest Minutes */
            longest_minutes: number;
            /** Median Minutes */
            median_minutes: number;
            /**
             * Resolved Calls
             * @description Calls that reached a resolution. Every figure here is measured over these only — handle time across all calls rewards ending the call, not solving it.
             */
            resolved_calls: number;
            /** Total Calls */
            total_calls: number;
        };
        /**
         * RiskFactorResponse
         * @description One column of the signal matrix.
         */
        RiskFactorResponse: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Short Label */
            short_label: string;
        };
        /** RunItemResponse */
        RunItemResponse: {
            /** Call Id */
            call_id: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Finished At */
            finished_at: string | null;
            /** Message */
            message: string;
            /** Reference */
            reference: string;
            /** Source Id */
            source_id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** RunResponse */
        RunResponse: {
            /** Can Resume */
            can_resume: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Force */
            force: boolean;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Items */
            items: components["schemas"]["RunItemResponse"][];
            /** Message */
            message: string;
            /** Model */
            model: string;
            progress: components["schemas"]["ProgressResponse"];
            /** Provider */
            provider: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** RunSummaryResponse */
        RunSummaryResponse: {
            /** Can Resume */
            can_resume: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Force */
            force: boolean;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Message */
            message: string;
            /** Model */
            model: string;
            progress: components["schemas"]["ProgressResponse"];
            /** Provider */
            provider: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** ScoreResponse */
        ScoreResponse: {
            /** Applied Offset */
            applied_offset: number;
            /** Gate Messages */
            gate_messages: string[];
            /** Status */
            status: string;
            /** Tier */
            tier: string;
            /** Total Negative */
            total_negative: number;
            /** Total Positive */
            total_positive: number;
            /** Value */
            value: number;
        };
        /** SentimentMovementResponse */
        SentimentMovementResponse: {
            /** Improved */
            improved: number;
            /** Improved Rate */
            improved_rate: number;
            /** Unchanged */
            unchanged: number;
            /** Unclassified */
            unclassified: number;
            /** Worsened */
            worsened: number;
        };
        /** SignalEntryResponse */
        SignalEntryResponse: {
            /** Code */
            code: string;
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Owner */
            owner: string;
            /** Percentage Of Corpus */
            percentage_of_corpus: number;
        };
        /** SignalTypeEntry */
        SignalTypeEntry: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Severity */
            severity: string;
        };
        /** SignalsResponse */
        SignalsResponse: {
            /**
             * Categories
             * @description Every configured L4 category, including those with no signals — the absence is shown rather than implied.
             */
            categories: components["schemas"]["SignalEntryResponse"][];
            /** Owners */
            owners: components["schemas"]["OwnerLoadResponse"][];
        };
        /** StartRunRequest */
        StartRunRequest: {
            /**
             * Acknowledge Cost
             * @description Required to run against a provider that charges per token.
             * @default false
             */
            acknowledge_cost: boolean;
            /**
             * Force
             * @description Re-analyse calls that already have an analysis, replacing them.
             * @default false
             */
            force: boolean;
            /**
             * Model
             * @description Model override for this run.
             */
            model?: string | null;
            /**
             * Provider
             * @description Provider name. Defaults to the configured provider.
             */
            provider?: string | null;
        };
        /** TaxonomyResponse */
        TaxonomyResponse: {
            /** Caller Types */
            caller_types: string[];
            /** Categories */
            categories: components["schemas"]["CategoryEntry"][];
            /** L4 Categories */
            l4_categories: components["schemas"]["L4CategoryEntry"][];
            /** Resolutions */
            resolutions: string[];
            /** Rubric Version */
            rubric_version: string;
            /** Sentiment States */
            sentiment_states: string[];
            /** Severities */
            severities: string[];
            /** Signal Types */
            signal_types: components["schemas"]["SignalTypeEntry"][];
            tiers: components["schemas"]["TierThresholdsEntry"];
        };
        /** TierThresholdsEntry */
        TierThresholdsEntry: {
            /** Average */
            average: number;
            /** Good */
            good: number;
            /** Min Calls For Tier Rating */
            min_calls_for_tier_rating: number;
        };
        /** TimeValueResponse */
        TimeValueResponse: {
            /**
             * Categories
             * @description Most time first. Categories with no timed calls are omitted.
             */
            categories: components["schemas"]["CategoryMinutesResponse"][];
            /** @description Ended without an answer in less time than a typical successful call — a member brushed off. A coaching signal. */
            fast_fail: components["schemas"]["FailureModeResponse"];
            /**
             * Productive Share
             * @description Share of all minutes spent on calls that reached a resolution.
             */
            productive_share: number;
            /**
             * Resolved Median Minutes
             * @description Median duration of a resolved call, and the line dividing the two failure modes. Derived from the corpus, not configured.
             */
            resolved_median_minutes: number;
            /** Resolved Minutes */
            resolved_minutes: number;
            /** @description Ended without an answer having taken at least as long as a typical successful call — the work was done and the system had no answer. A process signal, and coaching these agents would be the wrong response. */
            slow_fail: components["schemas"]["FailureModeResponse"];
            /** Total Minutes */
            total_minutes: number;
            /** Unproductive Minutes */
            unproductive_minutes: number;
        };
        /**
         * TrendDeltaResponse
         * @description The most recent week against the one before it.
         */
        TrendDeltaResponse: {
            /** Calls */
            calls: number;
            /** Escalation Rate */
            escalation_rate: number | null;
            /** Median Handle Minutes */
            median_handle_minutes: number | null;
            /** Median Score */
            median_score: number | null;
            /** Resolution Rate */
            resolution_rate: number | null;
        };
        /** TrendPointResponse */
        TrendPointResponse: {
            /** Calls */
            calls: number;
            /**
             * Escalation Rate
             * @description The share of this period's calls that escalated. Absent for a period with no calls; 0 means calls were analysed and none escalated.
             */
            escalation_rate?: number | null;
            /** Label */
            label: string;
            /** Median Handle Minutes */
            median_handle_minutes?: number | null;
            /**
             * Median Score
             * @description Absent for a week with no calls, which is a gap not a zero.
             */
            median_score?: number | null;
            /** Resolution Rate */
            resolution_rate?: number | null;
            /**
             * Starting
             * Format: date
             */
            starting: string;
        };
        /** TurnResponse */
        TurnResponse: {
            /** Role */
            role: string;
            /** Seq */
            seq: number;
            /** Speaker Name */
            speaker_name: string | null;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkMixResponse */
        WorkMixResponse: {
            /** Busiest Hour */
            busiest_hour: string | null;
            /** Caller Total */
            caller_total: number;
            /** Callers */
            callers: components["schemas"]["CallerBreakdownResponse"][];
            /** Hours */
            hours: components["schemas"]["HourlyPointResponse"][];
            /** Unattributed Calls */
            unattributed_calls: number;
            /** Weakest Hour */
            weakest_hour: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyse_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calls_api_v1_calls_get: {
        parameters: {
            query?: {
                /** @description Call category code. */
                category?: string | null;
                /** @description Agent name. */
                agent?: string | null;
                /** @description Outcome, e.g. UNRESOLVED. */
                resolution?: string | null;
                max_score?: number | null;
                min_score?: number | null;
                has_broker_signal?: boolean | null;
                /** @description Broker name attributed on the call. */
                broker?: string | null;
                /** @description Who called: MEMBER, EMPLOYER or BROKER. */
                caller?: string | null;
                /** @description Member identifier, as stated in the call. */
                member?: string | null;
                /** @description Signal code, e.g. clinical_risk. */
                signal?: string | null;
                /** @description The hour of the day a call started, 0-23, in the wall-clock the source stated. Matches the hourly chart's bars. */
                hour?: number | null;
                /** @description L4 finding category code. The finding taxonomy, not the call category: a Coverage & Benefits call can raise a Process Breakdown finding. */
                l4_category?: string | null;
                /** @description Matches title, summary or reference. */
                search?: string | null;
                /** @description Column to order by. 'severity' is what needs action first. */
                sort?: components["schemas"]["CallSort"];
                direction?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallsPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_call_api_v1_calls__call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    corpus_status_api_v1_corpus_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusStatusResponse"];
                };
            };
        };
    };
    clear_corpus_api_v1_corpus_analyses_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearedCorpusResponse"];
                };
            };
        };
    };
    list_corpus_imports_api_v1_corpus_imports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusVersionResponse"][];
                };
            };
        };
    };
    import_corpus_api_v1_corpus_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_corpus_api_v1_corpus_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_corpus_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_v1_corpus_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_corpus_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_corpus_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_v1_corpus_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_v1_corpus_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agents_api_v1_dashboard_agents_get: {
        parameters: {
            query?: {
                /** @description Narrow to calls from the week containing this date. */
                anchor?: string | null;
                /** @description Narrow to calls from this date's calendar month. */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brokers_api_v1_dashboard_brokers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerResponse"][];
                };
            };
        };
    };
    get_effort_api_v1_dashboard_effort_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffortResponse"];
                };
            };
        };
    };
    get_members_at_risk_api_v1_dashboard_members_at_risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembersAtRiskResponse"];
                };
            };
        };
    };
    get_overview_api_v1_dashboard_overview_get: {
        parameters: {
            query?: {
                /** @description Narrow every figure to the week containing this date. */
                anchor?: string | null;
                /** @description Narrow every figure to this date's calendar month. */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pulse_api_v1_dashboard_pulse_get: {
        parameters: {
            query?: {
                /** @description End the window on the week containing this date. */
                anchor?: string | null;
                /** @description Every week of this date's calendar month, instead of a trailing window. */
                month?: string | null;
                /** @description The week either side of this date's own week, instead of a trailing window. Empty if this date does not fall in any week the corpus has. */
                centre?: string | null;
                /** @description What one point covers. Months are re-bucketed from the calls themselves, so a month's median is the median of its own calls and not the median of its weekly medians. */
                bucket?: components["schemas"]["Bucket"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PulseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resolution_time_api_v1_dashboard_resolution_time_get: {
        parameters: {
            query?: {
                /** @description Narrow to calls from the week containing this date. */
                anchor?: string | null;
                /** @description Narrow to calls from this date's calendar month. */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolutionTimeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_signals_api_v1_dashboard_signals_get: {
        parameters: {
            query?: {
                /** @description Narrow to calls from the week containing this date. */
                anchor?: string | null;
                /** @description Narrow to calls from this date's calendar month. */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_time_value_api_v1_dashboard_time_value_get: {
        parameters: {
            query?: {
                /** @description Narrow to calls from the week containing this date. */
                anchor?: string | null;
                /** @description Narrow to calls from this date's calendar month. */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeValueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_mix_api_v1_dashboard_work_mix_get: {
        parameters: {
            query?: {
                /** @description Narrow to calls from the week containing this date. */
                anchor?: string | null;
                /** @description Narrow to calls from this date's calendar month. */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkMixResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A component is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_providers_api_v1_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersResponse"];
                };
            };
        };
    };
    get_taxonomy_api_v1_taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyResponse"];
                };
            };
        };
    };
}
